services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vite_dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host

  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    container_name: vite_builder
    volumes:
      - dist:/app/dist
    command: echo "Build complete"
  prod:
    image: nginx:stable-alpine
    container_name: vite_prod
    ports:
      - "8080:80"
    volumes:
      - dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - builder

volumes:
  dist:
